version: '3.8'

services:
  master:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: u1
      MYSQL_PASSWORD: p1
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --server-id=1
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql

  replica-1:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: u2
      MYSQL_PASSWORD: p2
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --server-id=2
    ports:
      - "3307:3306"
    volumes:
      - replica1_data:/var/lib/mysql

  replica-2:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: u3
      MYSQL_PASSWORD: p3
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --server-id=3
    ports:
      - "3308:3306"
    volumes:
      - replica2_data:/var/lib/mysql


  proxysql:
    image: proxysql/proxysql:latest
    platform: linux/amd64
    ports:
      - "6032:6032"  # Port for admin interface
      - "6033:6033"  # Port for client connections
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf  # Assuming you have a configuration file
      - .:/var/lib/proxysql
    depends_on:
      - master
      - replica-1
      - replica-2

volumes:
  master_data:
  replica1_data:
  replica2_data: